### ISSUE TITLE
命令行很方便呀，但是用不了，不再维护了？

### ISSUE THREAD

**Issue by liangzhdp** [Leezj9671/12306TicketsSearch#1]
>>> /usr/bin/tickets 广州 深圳 2019-09-02
/usr/lib/python3.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python3.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/usr/bin/tickets", line 11, in <module>
    load_entry_point('tickets==1.0', 'console_scripts', 'tickets')()
  File "/usr/lib/python3.7/site-packages/tickets-1.0-py3.7.egg/show.py", line 49, in cli
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 894, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Leezj9671** [comment]
是的，现在不维护了，但总体思路应该还是对的。我看你的错误似乎也跟ssl有关，请试试添加证书或配置urllib3不认证https网站吧。
